version: '3.5'
services:
  db:
    # docker run --name postgres_db -e POSTGRES_DB=test -e POSTGRES_USER=123 -e POSTGRES_PASSWORD=123 -e PGDATA=/var/lib/postgresql/data/pgdata  -p 5432:5432 -d postgres:13.3
    container_name: 'postgres_db'
    image: postgres:13.3
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: 123
      POSTGRES_PASSWORD: 123
      PGDATA: /var/lib/postgresql/data/pgdata
      # POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    ports:
      - "5432:5432"

    volumes:
      - target:/var/run/postgresql/
      - pgdata:/var/lib/postgresql/data/

    networks:
      - test_net

  web:
    container_name: 'ec_site'
    # command: uwsgi --ini /web/ec_site/uwsgi.ini
    # command: python manage.py runserver
    # command: ./server_run.sh
    entrypoint: ./server_run.sh
    # entrypoint: /web/server_run.sh
    # build:說明此容器要使用特定 Dockerfile 來 build
    build:
      # context為檔案目錄
      context: ./ec_site
      # dockerfile為 Dockerfile 的名字。
      dockerfile: Dockerfile

      # command:
    restart: always
    volumes:
      - api_data:/web
      - target:/var/run/postgresql/
      - ./ec_site/ec_site/settings.py:/web/ec_site/settings.py
      - ./ec_site/ec_site/uwsgi.ini:/web/ec_site/uwsgi.ini
      - ./ec_site/ec_site/views.py:/web/ec_site/views.py
      # - /Users/lionl771128/Documents/Django_test/ec_site/web:/web
    depends_on:
      - db
    networks:
      - test_net

  nginx:
    container_name: nginx-container
    build:
      # context為檔案目錄
      context: ./nginx
      # dockerfile為 Dockerfile 的名字。
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    volumes:
      - api_data:/web
      - ./log:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/mysite_nginx.conf:/etc/nginx/sites-enabled/mysite_nginx.conf
      # - /Users/lionl771128/Documents/Django_test/ec_site/web:/web
    depends_on:
      - web
    networks:
      - test_net

volumes:
  api_data:
  pgdata:
  target:

networks:
  test_net:
    driver: bridge